name: Terraform Deployment

on:
  push:
    branches:
      - feat-checkov-integation  # or 'master', depending on your default branch

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install Docker
        run: |
          sudo yum update -y
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo systemctl enable docker
          sudo usermod -a -G docker ec2-user        

  

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform 

      - name: 🧰 Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  




          
